services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fourallportal\Fourallportalext\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Api/*'

  Fourallportal\Fourallportalext\Api\File:
    public: true
    autowire: false